Repository tibue99/ezcord, pull requests merged in 2024-03, with the labels that each got.

#59 feat: add message utils
  ezcord/errors.py
  ezcord/utils.py
Labels: enhancement

#58 feat: add localization support
  docs/examples/examples.rst
  docs/examples/localization.rst
  docs/ezcord/i18n.rst
  docs/ezcord/modules.rst
  examples/localization/commands.yaml
  examples/localization/en.yaml
  examples/localization/example_cog.py
  examples/localization/localization.py
  ezcord/__init__.py
  ezcord/bot.py
  ezcord/cogs/blacklist.py
  ezcord/cogs/help.py
  ezcord/emb.py
  ezcord/i18n.py
  ezcord/internal/__init__.py
  ezcord/internal/config.py
  ezcord/internal/language/languages.py
  ezcord/internal/translation.py
  ezcord/times.py
Labels: enhancement

#61 feat: improve i18n
  ezcord/i18n.py
Labels: enhancement

#62 feat: allow usage without a supported discord library
  ezcord/internal/dc/__init__.py
  ezcord/internal/embed_templates.py
Labels: bug

#63 docs: add contribution guide
  README.md
  dev-requirements.txt
  docs/index.rst
  docs/pages/contributing.rst
Labels: documentation
